name       : exercism-cli
version    : 3.0.12
release    : 3
source     :
    - https://github.com/exercism/cli/archive/v3.0.12.tar.gz : cdafd383d866dca4bc96be002d5d25eeea4801d003456a0215e28a2fba5a0820
license    : MIT
component  : programming
summary    : A command line tool for exercism.io
description: |
    A command line tool for exercism.io, this provides a way to do the problems on exercism.io.
networking : yes
builddeps  :
    - git
    - golang
setup      : |
    mkdir -p src/github.com/exercism/cli
    mv api bin browser cli cmd config debug exercism fixtures shell workspace go.mod go.sum src/github.com/exercism/cli
build      : |
    export GOPATH=$(pwd)
    export GO111MODULE=on
    cd src/github.com/exercism/cli
    go get ./...
    go build -o build/exercism exercism/main.go
install    : |
    cd src/github.com/exercism/cli
    install -Dm00755 build/exercism $installdir/usr/bin/exercism
