name       : exercism-cli
version    : 3.0.11
release    : 2
source     :
    - https://github.com/exercism/cli/archive/v3.0.11.tar.gz : 544088bc562a8624e3527dd9d3ccf944dc4923b644bcdf49ef04e6d0ee48ddad
license    : MIT
component  : programming
summary    : A command line tool for exercism.io
description: |
    A command line tool for exercism.io, this provides a way to do the problems on exercism.io.
networking : yes
builddeps  :
    - dep
    - git
    - golang
setup      : |
    mkdir -p src/github.com/exercism/cli
    mv api bin browser cli cmd config debug exercism fixtures shell workspace Gopkg.toml src/github.com/exercism/cli
build      : |
    export GOPATH=$(pwd)
    cd src/github.com/exercism/cli
    dep ensure -v
    go build -o build/exercism exercism/main.go
install    : |
    cd src/github.com/exercism/cli
    install -Dm00755 build/exercism $installdir/usr/bin/exercism