name       : exercism-cli
version    : 2.3.0
release    : 1
source     :
    - https://github.com/exercism/cli/archive/v2.3.0.tar.gz : ca1432af80f9257c4c06107d0d1732845d49ac450f56ea04bcf58ead46d0af74
license    : MIT
component  : programming
summary    : A command line tool for exercism.io
description: |
    A command line tool for exercism.io, this provides a way to do the problems on exercism.io.
builddeps  :
    - golang
setup      : |
    mkdir -p src/github.com/exercism/cli
    mv api bin cmd config debug exercism fixtures paths user vendor src/github.com/exercism/cli/
build      : |
    export GOPATH=$(pwd)
    go build -v -o build/exercism src/github.com/exercism/cli/exercism/main.go
install    : |
    install -Dm755 build/exercism $installdir/usr/bin/exercism
