name       : exercism-cli
version    : 3.0.13
release    : 6
source     :
    - https://github.com/exercism/cli/archive/v3.0.13.tar.gz : ecc27f272792bc8909d14f11dd08f0d2e9bde4cc663b3769e00eab6e65328a9f
license    : MIT
component  : programming
summary    : A command line tool for exercism.io
description: |
    A command line tool for exercism.io, this provides a way to do the problems on exercism.io.
networking : yes
builddeps  :
    - git
    - golang
setup      : |
    mkdir -p src/github.com/exercism/cli
    mv api browser cli cmd config debug exercism fixtures shell workspace go.mod go.sum src/github.com/exercism/cli
build      : |
    export GOPATH=$(pwd)
    export GO111MODULE=on
    cd src/github.com/exercism/cli
    go get ./...
    go build -o build/exercism exercism/main.go
install    : |
    cd src/github.com/exercism/cli
    install -Dm00755 build/exercism $installdir/usr/bin/exercism
